/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _STUDENT_H_RPCGEN
#define _STUDENT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct student {
	int id;
	char *name;
	int age;
};
typedef struct student student;

#define STUDENT_PROG 0x01234567
#define STUDENT_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define create 1
extern  int * create_1(student *, CLIENT *);
extern  int * create_1_svc(student *, struct svc_req *);
#define read 2
extern  student * read_1(int *, CLIENT *);
extern  student * read_1_svc(int *, struct svc_req *);
extern int student_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define create 1
extern  int * create_1();
extern  int * create_1_svc();
#define read 2
extern  student * read_1();
extern  student * read_1_svc();
extern int student_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_student (XDR *, student*);

#else /* K&R C */
extern bool_t xdr_student ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_STUDENT_H_RPCGEN */
