/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "student.h"

static student DB[100];
static count = 0;
int *
create_1_svc(student *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

        DB[count] = *argp;
        count += 1;
        

	return &result;
}

student *
read_1_svc(int *argp, struct svc_req *rqstp)
{
	static student  result;

	/*
	 * insert server code here
	 */

        for(int i = 0; i < count; i++) {
                if(DB[i].id == *argp) {
                        result = DB[i];
                }
        }

	return &result;
}
